### ISSUE TITLE
App won't close even pop() or press back button on the last page

### ISSUE THREAD

**Issue by rururux** [lulupointu/vrouter#16]
I noticed this while developing my own app, and when I tried it with the [official example](https://github.com/lulupointu/vrouter/blob/main/example/lib/main.dart), the same problem occurred.

Here is the error log. Also, the same error is displayed even when pop() succeeds when there are other pages.

```console
E/flutter ( 5908): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
E/flutter ( 5908): Receiver: null
E/flutter ( 5908): Tried calling: length
E/flutter ( 5908): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 5908): #1      Uri.parse (dart:core/uri.dart:726:17)
E/flutter ( 5908): #2      VRouterState._updateUrl (package:vrouter/src/router.dart:1065)
E/flutter ( 5908): #3      VRouterState._pop (package:vrouter/src/router.dart:1516)
E/flutter ( 5908): #4      VRouterState.systemPop (package:vrouter/src/router.dart:1948)
E/flutter ( 5908): #5      VRouterData.systemPop (package:vrouter/src/router.dart:2127)
E/flutter ( 5908): #6      _VRouteState.build.<anonymous closure> (package:vrouter/src/route.dart:67)
E/flutter ( 5908): #7      _VRouteState.build.<anonymous closure> (package:vrouter/src/route.dart:66)
E/flutter ( 5908): #8      VRouterDelegate.popRoute (package:vrouter/src/navigation_2_wrappers.dart:497)
E/flutter ( 5908): #9      _RouterState._handleBackButtonDispatcherNotification (package:flutter/…/widgets/router.dart:613)
E/flutter ( 5908): #10     _CallbackHookProvider.invokeCallback (package:flutter/…/widgets/router.dart:767)
E/flutter ( 5908): #11     BackButtonDispatcher.invokeCallback (package:flutter/…/widgets/router.dart:851)
E/flutter ( 5908): #12     RootBackButtonDispatcher.didPopRoute (package:flutter/…/widgets/router.dart:944)
E/flutter ( 5908): #13     WidgetsBinding.handlePopRoute (package:flutter/…/widgets/binding.dart:635)
E/flutter ( 5908): <asynchronous suspension>
E/flutter ( 5908): #14     MethodChannel._handleAsMethodCall (package:flutter/…/services/platform_channel.dart:435)
E/flutter ( 5908): <asynchronous suspension>
E/flutter ( 5908): #15     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/…/services/binding.dart:284)
E/flutter ( 5908): <asynchronous suspension>
E/flutter ( 5908):
```

**Comment by lulupointu** [comment]
Hi, are you using the nullsafe version or the other one?

**Comment by rururux** [comment]
Thanks for the quick reply.
I have checked with 0.0.14.
I just tried it now with 1.0.0-nullsafety.11 and the error is gone, but it did not solve the problem of the app not closing.

**Comment by lulupointu** [comment]
The nullsafe version does not have it because the package I need to do it has not migrates yet.

0.0.14 should work though, I'll have a look and let you know!

**Comment by rururux** [comment]
OK, Thank you😊

**Comment by lulupointu** [comment]
v0.0.15 should fix this, please reopen this issue if it did not.

Thanks for your interest in vrouter !

**Comment by rururux** [comment]
I checked it now and it is fixed.
Thanks for fix, and for great package!
