### ISSUE TITLE
Tried to get applicationInstanceId but it has not been set

### ISSUE THREAD

**Issue by sgehrman** [lulupointu/vrouter#163]
and 

"Error: Exception: Tried to get historyIndex but it has not been set

And I had the VRouterScope issue.  That isn't mentioned in teh docs.

Why do I get a ton of exceptions using this?

**Comment by lulupointu** [comment]
Are you using VRouter or VRouterDelegate ?

**Comment by sgehrman** [comment]
VRouter.  I have a basic setup. I'm doing nothing fancy.

Exception has occurred.
"Error: Exception: Tried to get applicationInstanceId but it has not been set
    at Object.throw_ [as throw] (http://localhost:8084/dart_sdk.js:5081:11)
    at Function.getApplicationInstanceId (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:3648:19)
    at Function._getInitialApplicationInstanceId (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:2798:72)
    at new vurl_history_web.VHistoryWeb.new (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:2894:64)
    at Function.implementation (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:2644:44)
    at new vrouter_scope._VRouterScopeState.new (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:9083:47)
    at vrouter_scope.VRouterScope.new.createState (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:9014:14)
    at new framework.StatefulElement.new (http://localhost:8084/packages/flutter/src/widgets/widget_inspector.dart.lib.js:50658:33)
    at vrouter_scope.VRouterScope.new.createElement (http://localhost:8084/packages/flutter/src/widgets/widget_inspector.dart.lib.js:12634:14)

**Comment by lulupointu** [comment]
Are you using the latest version of VRouter?
In any case I would need a small reproducible example since it looks like you are reaching an edge case. Is this happening with the example app?

**Comment by sgehrman** [comment]
Have you tried running it in the debugger with all exceptions turned on? 
As far as I know I'm just doing the normal recommended way, but I can check more closely.

**Comment by sgehrman** [comment]
![gnome-shell-screenshot-U7LLC1](https://user-images.githubusercontent.com/287137/141598159-7714efe1-b17b-4ab2-ae75-b59c1a5e1a5a.png)

**Comment by sgehrman** [comment]
globalState is null

**Comment by sgehrman** [comment]
I can't debug with exceptions turned on. Vrouter is constantly crashing

Exception has occurred.
"Error: Bad state: No element
    at Object.throw_ [as throw] (http://localhost:8084/dart_sdk.js:5081:11)
    at Array.[dartx.firstWhere] (http://localhost:8084/dart_sdk.js:16761:19)
    at vrouter_delegate.VRouterDelegate.new._updateUrl (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:4057:74)
    at _updateUrl.next (<anonymous>)
    at runBody (http://localhost:8084/dart_sdk.js:40064:34)
    at Object._async [as async] (http://localhost:8084/dart_sdk.js:40095:7)
    at vrouter_delegate.VRouterDelegate.new.[_updateUrl] (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:4042:20)
    at vrouter_delegate.VRouterDelegate.new._pop (http://localhost:8084/packages/vrouter/src/widgets/anchor/hovering_overlay.dart.lib.js:4202:27)
    at _pop.next (<anonymous>)
    at http://localhost:8084/dart_sdk.js:40045:33
    at _RootZone.runUnary (http://localhost:8084/dart_sdk.js:39916:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:8084/dart_sdk.js:34863:29)
    at handleValueCallback (http://localhost:8084/dart_sdk.js:35430:49)
    at Function._propagateToListeners (http://localhost:8084/dart_sdk.js:35468:17)
    at _Future.new.[_completeWithValue] (http://localhost:8084/dart_sdk.js:35316:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:8084/dart_sdk.js:35337:35)
    at Object._microtaskLoop (http://localhost:8084/dart_sdk.js:40183:13)
    at _startMicrotaskLoop (http://localhost:8084/dart_sdk.js:40189:13)
    at http://localhost:8084/dart_sdk.js:35688:9"

**Comment by sgehrman** [comment]
![gnome-shell-screenshot-F69SC1](https://user-images.githubusercontent.com/287137/141663349-e82a230b-fa30-49eb-931c-87870ccbe35a.png)

**Comment by lulupointu** [comment]
I'm sorry but without being able to reproduce the issue I can't really help you.

Plus I'm not sure what is your issue. The [first exception](https://github.com/lulupointu/vrouter/issues/163#issuecomment-964786742) you shared was 
> Tried to get applicationInstanceId but it has not been set

But [the second](https://github.com/lulupointu/vrouter/issues/163#issuecomment-968182325) is 
> Bad state: No element

Which one is it and how to reproduce it? 

<details>
<summary>
Using the following example
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(
    VRouter(
      debugShowCheckedModeBanner: false,
      routes: [
        VNester(
          path: '/user', // We use '/user' so that [VNester.stackedRoute] knows on what to pop
          widgetBuilder: (child) => MyScaffold(child), // Child is the widget from nestedRoutes
          nestedRoutes: [
            VWidget(path: '/', widget: HomeScreen()),
            VWidget(
              key: ValueKey('UserScreen'),
              // We use a key to indicate that path and alias lead to the same screen
              path: null,
              // null path matches parent
              aliases: ['/settings'],
              // We use an alias because we need [VNester] to know what to use as a nestedRoute when on '/settings'
              widget: UserScreen(),
            ),
          ],
          stackedRoutes: [
            VWidget(path: '/settings', widget: SettingsScreen()),
          ],
        ),
      ],
    ),
  );
}

class BaseWidget extends StatelessWidget {
  final String title;

  final String buttonText;

  final String to;

  const BaseWidget({
    Key? key,
    required this.title,
    required this.buttonText,
    required this.to,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        appBar: AppBar(title: Text(title)),
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(title),
              SizedBox(height: 50),
              ElevatedButton(
                onPressed: () => context.vRouter.to(to),
                child: Text(buttonText),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class MyScaffold extends StatelessWidget {
  final Widget child;

  const MyScaffold(this.child);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: child,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: context.vRouter.url.contains('user') ? 1 : 0,
        onTap: (value) => context.vRouter.to((value == 0) ? '/' : '/user'),
        items: [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.person), label: 'User'),
        ],
      ),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BaseWidget(title: 'Home', buttonText: 'Go to User', to: '/user');
  }
}

class UserScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BaseWidget(title: 'User', buttonText: 'Go to Settings', to: '/settings');
  }
}

class SettingsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BaseWidget(title: 'Settings', buttonText: 'Go to User', to: '/user');
  }
}
```
</details>

With `flutter v2.5.3` and `vrouter v1.2.0+14` works perfectly no matter what I do (launch the app, navigate programmatically, deep-linking, manually change the url)
