### ISSUE TITLE
Failed to use context.vRouter.pushReplacementNamed

### ISSUE THREAD

**Issue by JigneshPatel23** [lulupointu/vrouter#23]
channel: dev
```
  vrouter: 
    git: 
      url: https://github.com/lulupointu/vrouter.git
      ref: dev
```

Failed: context.vRouter.pushReplacementNamed(kRouteAuthLogin);

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following UnsupportedError was thrown while handling a gesture:
flutter: Unsupported operation: Cannot modify an unmodifiable Map
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _ImmutableMap.updateAll (dart:core-patch/immutable_map.dart:114:5)
flutter: #1      VRouterState._updateUrlFromName (package:vrouter/src/vrouter/vrouter.dart:776:20)
flutter: #2      VRouterState.pushReplacementNamed (package:vrouter/src/vrouter/vrouter.dart:1618:5)
flutter: #3      RootVRouterData.pushReplacementNamed (package:vrouter/src/vrouter/root_vrouter_data.dart:111:14)
flutter: #4      LocalVRouterData.pushReplacementNamed (package:vrouter/src/vrouter/local_vrouter_data.dart:170:51)
flutter: #5      EmailOptions.build.<anonymous closure> (package:tictic/application/ui/authentication/view/auth_main_page.dart:97:35)
flutter: #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
flutter: #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
flutter: #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
flutter: #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
flutter: #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
flutter: #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
flutter: #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
flutter: #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
flutter: #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
flutter: #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
flutter: #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
flutter: #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
flutter: #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
flutter: #20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
flutter: #21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
flutter: #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
flutter: #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
flutter: #27     _invoke1 (dart:ui/hooks.dart:180:10)
flutter: #28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
flutter: #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: Handler: "onTap"
flutter: Recognizer:
flutter:   TapGestureRecognizer#77eb1
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Unsupported operation: Cannot modify an unmodifiable Map
flutter: Another exception was thrown: Unsupported operation: Cannot modify an unmodifiable Map
flutter: Another exception was thrown: Unsupported operation: Cannot modify an unmodifiable Map
flutter: Another exception was thrown: Unsupported operation: Cannot modify an unmodifiable Map

```

**Comment by JigneshPatel23** [comment]
This option works for me, maybe I am using this in unexpected way or not sure..

```
context.vRouter.pushReplacement(kRouteAuthLogin);
```

**Comment by lulupointu** [comment]
i will have a look at `pushReplacementNamed`. I leave this open as a reminder.

thanks for the report

**Comment by lulupointu** [comment]
Oh wait you used `Named` with a path? If so this is unexpected.
You should use `Named` with a VWidget which uses the `name` attribute for example. 

In any case, can you describe your use case (even if mis used) so that I can work on displaying a more helpful error message?

**Comment by JigneshPatel23** [comment]
Yes @lulupointu I have used `Named` with a path..

Yeah good catch, we can improve on more helpful error message..

**Comment by lulupointu** [comment]
After looking into it, what you encountered was definitely a bug. A more helpful error message should and will now be displayed.

This is silly since my tests did catch the issue, I just did forgot to run them.

In any case, thanks !
