### ISSUE TITLE
[Android] Unable to exit app on system pop (back button)

### ISSUE THREAD

**Issue by Poweranimal** [lulupointu/vrouter#27]
Using the VRouter I cannot exit my Android app on system pop (back button press) even though the initial route is presented.

ERROR:
```
E/flutter ( 6627): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method moveTaskToBack on channel move_to_background)
E/flutter ( 6627): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6627): <asynchronous suspension>
E/flutter ( 6627): #1      MoveToBackground.moveTaskToBack (package:vrouter/wrappers/move_to_background.dart:19:7)
E/flutter ( 6627): <asynchronous suspension>
E/flutter ( 6627): 
```

Device:
    OS:           Android
    Version:    30
    Device:     Pixel 4
    CPU/ABI:  x86_64
    Emulator:  true

**Comment by lulupointu** [comment]
Can you

```
flutter clean
flutter pub get
```

Making sure that you are on the latest version on VRouter (V1. 1.0+11)

**Comment by Poweranimal** [comment]
Well, `flutter clean` helped indeed.... xD
