### ISSUE TITLE
How to avoid the navigation assertion of "!pageKeyToOldEntry.containsKey(page.key) is not ture"

### ISSUE THREAD

**Issue by yellowgraysu** [lulupointu/vrouter#77]
I have 2 pages in the router. If I switch between pages too fast, it pops up an assertion: **"!pageKeyToOldEntry.containsKey(page.key) is not true"**

I think it is because the animation is not finished when trying to re-enter the same page again. How can I avoid it?

Thanks!

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      initialUrl: '/page1',
      routes: [
        VWidget(
          key: const ValueKey('page1'),
          path: '/page1',
          widget: Builder(
            builder: (context) {
              return TextButton(
                onPressed: () {
                  context.vRouter.push('/page2');
                },
                child: const Text('change'),
              );
            },
          ),
        ),
        VWidget(
          key: const ValueKey('page2'),
          path: '/page2',
          widget: Builder(
            builder: (context) {
              return TextButton(
                onPressed: () {
                  context.vRouter.push('/page1');
                },
                child: const Text('change'),
              );
            },
          ),
        ),
      ],
    );
  }
}
```

<details>
  <summary>Error message</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
Assertion failed: file:///C:/src/flutter/packages/flutter/lib/src/widgets/navigator.dart:3763:14
!pageKeyToOldEntry.containsKey(page.key)
is not true

The relevant error-causing widget was: 
  VRouter file:///C:/Users/User/AndroidStudioProjects/flutter_app_test2/lib/main.dart:11:12
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/widgets/navigator.dart 3763:49                                                                        [_updatePages]
packages/flutter/src/widgets/navigator.dart 3585:7                                                                         didUpdateWidget
packages/flutter/src/widgets/framework.dart 4774:57                                                                        update
...
====================================================================================================
Error: Assertion failed: file:///C:/src/flutter/packages/flutter/lib/src/widgets/navigator.dart:3900:12
_debugLocked && !_debugUpdatingPage
is not true
    at Object.throw_ [as throw] (http://localhost:7116/dart_sdk.js:5347:11)
    at Object.assertFailed (http://localhost:7116/dart_sdk.js:5283:15)
    at navigator$.NavigatorState.new.[_flushHistoryUpdates] (http://localhost:7116/packages/flutter/src/widgets/widget_span.dart.lib.js:24643:96)
    at http://localhost:7116/packages/flutter/src/widgets/widget_span.dart.lib.js:23522:47
    at thunk (http://localhost:7116/packages/flutter/src/scheduler/ticker.dart.lib.js:310:9)
    at _RootZone.runUnary (http://localhost:7116/dart_sdk.js:39024:58)
    at _FutureListener.then.handleValue (http://localhost:7116/dart_sdk.js:34010:29)
    at handleValueCallback (http://localhost:7116/dart_sdk.js:34570:49)
    at Function._propagateToListeners (http://localhost:7116/dart_sdk.js:34608:17)
    at _Future.new.[_completeWithValue] (http://localhost:7116/dart_sdk.js:34450:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:7116/dart_sdk.js:34473:35)
    at Object._microtaskLoop (http://localhost:7116/dart_sdk.js:39311:13)
    at _startMicrotaskLoop (http://localhost:7116/dart_sdk.js:39317:13)
    at http://localhost:7116/dart_sdk.js:34824:9
\```
</details>

**Comment by lulupointu** [comment]
Hi, 

You are right, this is because the animation is not finished, therefore you are inserting 2 pages with the same key in the `Navigator`.
This is not specific to `VRouter` but to flutter `Navigator`.

This is bad practice but not an error, it's an `assert`. This means that in `release` or `profile` mode this won't cause any error. You can try it. run `flutter run --profile` and mash that press button, nothing will go wrong :wink: 

I don't think you should bother yourself with this. This is bad practice because if you do something else quickly this could case issue but the probability for quickly switching+doing another navigation action which causes an issue, under 300 milliseconds, is not realistic

**Comment by yellowgraysu** [comment]
Awesome explanation!

Thank you

**Comment by SolweyWes** [comment]
Heya @lulupointu,

Not to be to much of a fuss, but I'm also getting this error with a client's far-progressed codebase now that we've added some animated page transitions.  As a contracting developer, I can't really deliver a final product to a client that heavily pollutes the console with stack traces or hits red-screen framework asserts in day-to-day coding/debugging workflows just because the issues will suppress during production.

Is there really no way to reconcile the framework asserts with the VRouter implementation?

**Comment by CosmicPangolin** [comment]
Heya @lulupointu,

Not to be to much of a fuss, but I'm also getting this error with a client's far-progressed codebase now that we've added some animated page transitions. As a contracting developer, I can't really deliver a final product to a client that heavily pollutes the console with stack traces or hits red-screen framework asserts in day-to-day coding/debugging workflows just because the issues will suppress during production.

Is there really no way to reconcile the framework asserts with the VRouter implementation?

**Comment by lulupointu** [comment]
@CosmicPangolin I'm sorry to hear it, but also quite surprised. This should only happen in extreme cases where you rapidly switch back and forth from a screen and the animation between the two is long enough that the screen did not finish animating before you navigate back to it.

However, there might be an other issue. The thing is that VRouter basically uses `VWidget.path` as a key, so if you have twice the same path in `VWidget` shown at the same time (and not separated by `VNester.subroutes`) then this will cause an issue for sure.
This is quite an edge case but might be worth looking into. 
<summary>
</summary>

**Comment by SolweyWes** [comment]
Yeah, in my case it's specifically because the client wants a header button that cycles between certain pages, which all have animated transitions...

I'll keep playing with my implementation and see if I can figure out a better solution :)

**Comment by CosmicPangolin** [comment]
Yeah, in my case it's specifically because the client wants a header button that cycles between certain pages, which all have animated transitions...

I'll keep playing with my implementation and see if I can figure out a better solution :)

**Comment by lulupointu** [comment]
If you can provide a small reproducible example I could certainly help, but since this is so specific I'm afraid I can't help you without. Please do as works best for you :)

**Comment by CosmicPangolin** [comment]
Yah definitely, here's a simple example that replicates a design I'm using for one set of pages:

```
class TransitionExample extends StatefulWidget {
  const TransitionExample({Key? key}) : super(key: key);

  @override
  _TransitionExampleState createState() => _TransitionExampleState();
}

class _TransitionExampleState extends State<TransitionExample> {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      routes: [
        VWidget(
          path: '/',
          widget: OnePage(),
          transitionDuration: Duration(
            milliseconds: 500,
          ),
          buildTransition: (animation, secondaryAnimation, child) =>
              FadeTransition(
            opacity: animation,
            child: child,
          ),
        ),
        VWidget(
          path: '/two',
          widget: TwoPage(),
          transitionDuration: Duration(
            milliseconds: 500,
          ),
          buildTransition: (animation, secondaryAnimation, child) =>
              FadeTransition(
            opacity: animation,
            child: child,
          ),
        ),
        VWidget(
          path: '/three',
          widget: ThreePage(),
          transitionDuration: Duration(
            milliseconds: 500,
          ),
          buildTransition: (animation, secondaryAnimation, child) =>
              FadeTransition(
            opacity: animation,
            child: child,
          ),
        ),
      ],
    );
  }
}

class OnePage extends StatefulWidget {
  const OnePage({Key? key}) : super(key: key);

  @override
  _OnePageState createState() => _OnePageState();
}

class _OnePageState extends State<OnePage> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          color: Colors.blue,
        ),
        Align(
          alignment: Alignment.centerLeft,
          child: ElevatedButton(
            child: Text('Prev'),
            onPressed: () => VRouter.of(context).to('/three'),
          ),
        ),
        Align(
          alignment: Alignment.centerRight,
          child: ElevatedButton(
            child: Text('Next'),
            onPressed: () => VRouter.of(context).to('/two'),
          ),
        ),
      ],
    );
  }
}

class TwoPage extends StatefulWidget {
  const TwoPage({Key? key}) : super(key: key);

  @override
  _TwoPageState createState() => _TwoPageState();
}

class _TwoPageState extends State<TwoPage> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          color: Colors.red,
        ),
        Align(
          alignment: Alignment.centerLeft,
          child: ElevatedButton(
            child: Text('Prev'),
            onPressed: () => VRouter.of(context).to('/'),
          ),
        ),
        Align(
          alignment: Alignment.centerRight,
          child: ElevatedButton(
            child: Text('Next'),
            onPressed: () => VRouter.of(context).to('/three'),
          ),
        ),
      ],
    );
  }
}

class ThreePage extends StatefulWidget {
  const ThreePage({Key? key}) : super(key: key);

  @override
  _ThreePageState createState() => _ThreePageState();
}

class _ThreePageState extends State<ThreePage> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          color: Colors.green,
        ),
        Align(
          alignment: Alignment.centerLeft,
          child: ElevatedButton(
            child: Text('Prev'),
            onPressed: () => VRouter.of(context).to('/two'),
          ),
        ),
        Align(
          alignment: Alignment.centerRight,
          child: ElevatedButton(
            child: Text('Next'),
            onPressed: () => VRouter.of(context).to('/'),
          ),
        ),
      ],
    );
  }
}

```

Given the longer fade animation between pages, if the developer cycles quickly between pages using one of the side buttons the assert throws.  Obviously this isn't an ideal user behavior, but between this page design and my nav header I run into the red screen of death about once per day while clicking between pages for testing.

**Comment by lulupointu** [comment]
Hi, finally got around to doing some proper testing. Here are my results.

I knew using custom key was a possibility but I also knew that it's not as simple as using random keys. Indeed the page rebuild its content when the key changes, therefore is you put a random key, stacking a page on top of another will cause the state of the lower page to be reloaded. The key, therefore, is to change key but not too often. I came up with a solution for your example which is quite elegant I would say.

<details>
<summary>
Here it is:
</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(TransitionExample());
}

class TransitionExample extends StatefulWidget {
  const TransitionExample({Key? key}) : super(key: key);

  @override
  _TransitionExampleState createState() => _TransitionExampleState();
}

class _TransitionExampleState extends State<TransitionExample> {
  // You could use a List but a unique value is enough since you
  // only need one at a time
  LocalKey _currentPageRandomKey = ValueKey(Random().nextDouble());

  // The static key of the previous visible page
  LocalKey? _previousPageStaticKey;

  // Updates the key if the given [pageIndex] is different from
  // the [_previousPageIndex]
  void _maybeUpdateRandomKey({required LocalKey staticKey}) {
    if (_previousPageStaticKey != staticKey) {
      _currentPageRandomKey = ValueKey(Random().nextDouble());
    }
    _previousPageStaticKey = staticKey;
  }

  @override
  Widget build(BuildContext context) {
    return VRouter(
      routes: [
        VPage(
          path: '/',
          widget: ColoredScreen(
            color: Colors.redAccent,
            nextUrl: '/two',
            previousUrl: '/three',
            hasStack: true,
          ),
          pageBuilder: (key, child, name) {
            _maybeUpdateRandomKey(staticKey: key);

            return FadingPage(
              key: _currentPageRandomKey,
              child: child,
              name: name,
            );
          },
          stackedRoutes: [
            VWidget.builder(
              path: 'stacked',
              builder: (context, _) => Material(
                child: Center(
                  child: ElevatedButton(
                    child: Text('Pop'),
                    onPressed: () => VRouter.of(context).to('/'),
                  ),
                ),
              ),
            ),
          ],
        ),
        VPage(
          path: '/two',
          widget: ColoredScreen(
            color: Colors.greenAccent,
            nextUrl: '/three',
            previousUrl: '/',
          ),
          pageBuilder: (key, child, name) {
            _maybeUpdateRandomKey(staticKey: key);

            return FadingPage(
              key: _currentPageRandomKey,
              child: child,
              name: name,
            );
          },
        ),
        VPage(
          path: '/three',
          widget: ColoredScreen(
            color: Colors.blueAccent,
            nextUrl: '/',
            previousUrl: '/two',
          ),
          pageBuilder: (key, child, name) {
            _maybeUpdateRandomKey(staticKey: key);

            return FadingPage(
              key: _currentPageRandomKey,
              child: child,
              name: name,
            );
          },
        ),
      ],
    );
  }
}

class ColoredScreen extends StatefulWidget {
  final Color color;

  final String previousUrl;

  final String nextUrl;

  final bool hasStack;

  const ColoredScreen({
    Key? key,
    required this.color,
    required this.previousUrl,
    required this.nextUrl,
    this.hasStack = false,
  }) : super(key: key);

  @override
  _ColoredScreenState createState() => _ColoredScreenState();
}

class _ColoredScreenState extends State<ColoredScreen> {
  @override
  void initState() {
    super.initState();

    print('initState color: ${widget.color}');
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(color: widget.color),
        Align(
          alignment: Alignment.centerLeft,
          child: ElevatedButton(
            child: Text('Prev'),
            onPressed: () => VRouter.of(context).to(widget.previousUrl),
          ),
        ),
        if (widget.hasStack)
          Align(
            alignment: Alignment.center,
            child: ElevatedButton(
              child: Text('Stack'),
              onPressed: () => VRouter.of(context).to('/stacked'),
            ),
          ),
        Align(
          alignment: Alignment.centerRight,
          child: ElevatedButton(
            child: Text('Next'),
            onPressed: () => VRouter.of(context).to(widget.nextUrl),
          ),
        ),
      ],
    );
  }
}

class FadingPage extends Page {
  final Widget child;

  final String? name;

  final LocalKey key;

  FadingPage({
    required this.key,
    required this.child,
    required this.name,
  }) : super(key: key);

  @override
  Route createRoute(BuildContext context) {
    return PageRouteBuilder(
      settings: this,
      pageBuilder: (_, __, ___) => child,
      transitionDuration: Duration(
        milliseconds: 500,
      ),
      transitionsBuilder: (context, animation, secondaryAnimation, child) => FadeTransition(
        opacity: animation,
        child: child,
      ),
    );
  }
}
```

</details>

Check the comment for the explanations and be sure to let me know if you have any issue!
