### ISSUE TITLE
App freezing while navigating.

### ISSUE THREAD

**Issue by sameep-baraiya** [lulupointu/vrouter#84]
Hello

I am have created very simple app with localization and nested route (for switching between screen). But when try to navigate it freezes every time.

https://user-images.githubusercontent.com/32372641/120684436-4d04fb80-c4bc-11eb-8d79-1ac30c210ab4.mp4

I can found this behaviour in android as well. But in android required more faster click between bottom navigation bar items.
Not sure what i am doing wrong here.

While web version not showing error properly but android version show following error.

![Screenshot_2021-06-03-22-41-20-503_com example bgmi_connect](https://user-images.githubusercontent.com/32372641/120685101-1e3b5500-c4bd-11eb-8e27-d61e5b5a5416.jpg)
![Screenshot_2021-06-03-22-42-01-283_com example bgmi_connect](https://user-images.githubusercontent.com/32372641/120685135-24c9cc80-c4bd-11eb-9929-8c44fe25f3fe.jpg)

**Code:**

main.dart:
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // Widget _fadeTransition(animation, _, child) => FadeTransition(
  //       opacity: animation,
  //       child: child,
  //     );

  @override
  Widget build(BuildContext context) => ChangeNotifierProvider(
      create: (context) => LocaleProvider(),
      builder: (context, child) {
        final provider = Provider.of<LocaleProvider>(context);

        return VRouter(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          locale: provider.locale,
          supportedLocales: L10n.all,
          localizationsDelegates: [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          routes: [
            VNester(
              path: '/',
              widgetBuilder: (child) => AppScreen(child: child),
              nestedRoutes: [
                VWidget(
                  path: '/',
                  widget: FeedsScreen(),
                  // buildTransition: _fadeTransition
                  // buildTransition: (animation, _, child) => SlideTransition(
                  //   position:
                  //       // -1.0 for left to right, 1.0 for right to left
                  //       Tween(begin: Offset(-1.0, 0.0), end: Offset(0.0, 0.0))
                  //           .animate(animation),
                  //   child: child,
                  // ),
                ),
                VWidget(
                  path: '/play',
                  widget: PlayScreen(),
                  // buildTransition: _fadeTransition,
                ),
                VWidget(
                  path: '/chat',
                  widget: ChatScreen(),
                  // buildTransition: _fadeTransition,
                ),
                VWidget(
                  path: '/more',
                  widget: MoreScreen(),
                  // buildTransition: _fadeTransition,
                ),
                VWidget(
                  path: '/notification',
                  widget: NotificationScreen(),
                  // buildTransition: _fadeTransition,
                ),
              ],
            ),
          ],
        );
      });
}
```

app_screen.dart:
```dart
class AppScreen extends StatelessWidget {
  final Widget child;
  const AppScreen({Key? key, required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(child: child),
      bottomNavigationBar: BottomBar(),
    );
  }
}

```

feeds_screen.dart: (similar for other screen)
```dart
class FeedsScreen extends StatelessWidget {
  const FeedsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.green,
      child: Text('Feeds'),
    );
  }
}

```

Thank You

**Comment by lulupointu** [comment]
Hi, I'm sorry but:
1. The video seems to be broken, I can't see it :/
2. Could you share your imports as well, I did not use localizations packages extensively so I'm not sure which package(s) you are using

Once at least 2 is fixed please comment and I'll have a look ! :)

**Comment by sameep-baraiya** [comment]
Hello @lulupointu,

New videos for web version:


https://user-images.githubusercontent.com/32372641/120753763-43fe4380-c529-11eb-9987-d96d8ccdd940.mp4


Web version error:
```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed:
package:flutter/…/painting/text_painter.dart:881
!_needsLayout
is not true

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/painting/text_painter.dart 881:13                        getPositionForOffset
packages/flutter/src/rendering/paragraph.dart 456:52                          hitTestChildren
packages/flutter/src/rendering/box.dart 2414:11                               hitTest
...
════════════════════════════════════════════════════════════════════════════════
```

Video for android version:


https://user-images.githubusercontent.com/32372641/120754445-4ca34980-c52a-11eb-8c31-981d0f3e60e4.mp4


Error for android version:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3784 pos 14: '!pageKeyToOldEntry.containsKey(page.key)': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
SafeArea
lib/screens/app_screen.dart:12
When the exception was thrown, this was the stack
#2      NavigatorState._updatePages
package:flutter/…/widgets/navigator.dart:3784
#3      NavigatorState.didUpdateWidget
package:flutter/…/widgets/navigator.dart:3606
#4      StatefulElement.update
package:flutter/…/widgets/framework.dart:4761
#5      Element.updateChild
package:flutter/…/widgets/framework.dart:3350
#6      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4599
...
════════════════════════════════════════════════════════════════════════════════
E/flutter ( 4379): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3921 pos 12: '_debugLocked && !_debugUpdatingPage': is not true.
E/flutter ( 4379): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 4379): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 4379): #2      NavigatorState._flushHistoryUpdates
package:flutter/…/widgets/navigator.dart:3921
E/flutter ( 4379): #3      _RouteEntry.handlePush.<anonymous closure>
package:flutter/…/widgets/navigator.dart:3020
E/flutter ( 4379): #4      TickerFuture.whenCompleteOrCancel.thunk
package:flutter/…/scheduler/ticker.dart:407
E/flutter ( 4379): #5      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 4379): #6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 4379): <asynchronous suspension>
E/flutter ( 4379): #7      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart)
package:flutter/…/scheduler/ticker.dart:1
E/flutter ( 4379): <asynchronous suspension>
E/flutter ( 4379):

════════ Exception caught by widgets library ═══════════════════════════════════
A GlobalKey was used multiple times inside one widget's child list.
The relevant error-causing widget was
SafeArea
lib/screens/app_screen.dart:12
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5307 pos 12: '!_debugLocked': is not true.
The relevant error-causing widget was
SafeArea
lib/screens/app_screen.dart:12
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 6111 pos 12: 'renderObject.child == child': is not true.
The relevant error-causing widget was
SafeArea
lib/screens/app_screen.dart:12
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Tried to build dirty widget in the wrong build scope.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 6111 pos 12: 'renderObject.child == child': is not true.
The relevant error-causing widget was
SafeArea
lib/screens/app_screen.dart:12
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
setState() or markNeedsBuild() called during build.
The relevant error-causing widget was
SafeArea
lib/screens/app_screen.dart:12
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
buildScope missed some dirty elements.
The list of dirty elements at the end of the buildScope call was
    BottomBar
        dependencies: [LocalVRouterData]
        state: _BottomBarState#cedbd
    ...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
A GlobalKey was used multiple times inside one widget's child list.
The relevant error-causing widget was
SafeArea
lib/screens/app_screen.dart:12
════════════════════════════════════════════════════════════════════════════════

```

Source Code:

https://github.com/sameep-baraiya/flutter_vrouter_localization

Thank You

**Comment by lulupointu** [comment]
Oh I see.

Please check this issue: https://github.com/lulupointu/vrouter/issues/77

Let me know if this is it !

**Comment by sameep-baraiya** [comment]
Hey it worked thank you 😊

> This is bad practice because if you do something else quickly this could cause issues.

I wanted to know way i code is bad practice or way i test app in debug mode is bad practice ? like should i worried about this issue ? Otherwise thank you. Great library.

**Comment by lulupointu** [comment]
You should not worry. This will never be an issue in production.

What is bad practice is not what you do nor the way you test (well tapping so fast is bad practice for your fingers surely but I'm no doctor :smile:).

**Comment by sameep-baraiya** [comment]
Thank You 😃 👍
