### ISSUE TITLE
Add routes dynamically with data coming from a Future

### ISSUE THREAD

**Issue by danieldoddjr** [lulupointu/vrouter#89]
We are trying to build routes dynamically. The route widgets wait for the data from a future. Using riverpods and change notifier this all happens. Initially we have an empty list but then after the future is done it updates with a list of the VWidgets. However the VRouter does not update when the data changes. Is there a way for this to happen with VRouter?  

```
void main() {
  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final viewsState = watch(viewsChangeNotifier);

    print(viewsState.getRoutes);

    return VRouter(
      debugShowCheckedModeBanner: false,
      mode: VRouterModes.history,
      routes: [
        VWidget(path: '/', widget: AuthenticationScreen()),
        VWidget(path: '/login', widget: LoginScreen()),
        VWidget(path: '/register', widget: RegisterScreen()),
        VWidget(path: '/view', widget: ViewScreen(route: 'about')),
        ...viewsState.getRoutes,
      ],
    );
  }
}
```

**Comment by lulupointu** [comment]
`routes` of `VRouter` are static by default and need not to change much.

You can however force a reload by changing the `navigatorKey`.

Here is an example:

![unknown](https://user-images.githubusercontent.com/5128921/121074524-40dab000-c7d4-11eb-8231-8860fe2211d8.png)

**Comment by danieldoddjr** [comment]
Thanks for the tip! Here is what I did.

```
void main() {
  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends ConsumerWidget {
  GlobalKey<NavigatorState> _navKey = GlobalKey<NavigatorState>();
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final viewsState = watch(viewsChangeNotifier);

    // If widgets in route array reset nav key
    if (viewsState.getRoutes.length > 0) {
      _navKey = GlobalKey<NavigatorState>();
    }

    return VRouter(
      debugShowCheckedModeBanner: false,
      mode: VRouterModes.history,
      navigatorKey: _navKey,
      routes: [
        VWidget(path: '/', widget: AuthenticationScreen()),
        VWidget(path: '/login', widget: LoginScreen()),
        VWidget(path: '/register', widget: RegisterScreen()),
        ...viewsState.getRoutes,
      ],
    );
  }
}
```

This works to get around for the user. The one issue I have is that on web if I hit refresh I get an inital error and then it rebuilds the nav key and then works.  Here is that error...

```
Error: The url '/shop' has no matching route.
Consider using VWidget(path: r':_(.*)', widget: UnknownPathWidget()) at the bottom of your VRouter routes to catch any wrong route.
    at Object.throw_ [as throw] (http://localhost:65255/dart_sdk.js:5037:11)
    at vrouter_delegate.VRouterDelegate.new._updateUrl (http://localhost:65255/packages/vrouter/src/vrouter_helpers.dart.lib.js:6145:23)
    at _updateUrl.next (<anonymous>)
    at runBody (http://localhost:65255/dart_sdk.js:37393:34)
```
Is there a cleaner way to do this?

**Comment by lulupointu** [comment]
The is because the url is `/shop` when you refresh, and the url is preserved on refresh (as it should).

To fix the easily you could add `VWidget(path: r':_(.*)', widget: Container()) ` (you could replace the Container with a splash screen for example). 
Add it only when there are no routes, like this:

```dart
void main() {
  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends ConsumerWidget {
  GlobalKey<NavigatorState> _navKey = GlobalKey<NavigatorState>();
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final viewsState = watch(viewsChangeNotifier);

    // If widgets in route array reset nav key
    if (viewsState.getRoutes.length > 0) {
      _navKey = GlobalKey<NavigatorState>();
    }

    return VRouter(
      debugShowCheckedModeBanner: false,
      mode: VRouterModes.history,
      navigatorKey: _navKey,
      routes: [
        VWidget(path: '/', widget: AuthenticationScreen()),
        VWidget(path: '/login', widget: LoginScreen()),
        VWidget(path: '/register', widget: RegisterScreen()),
        ...viewsState.getRoutes,

        if ( viewsState.getRoutes.length == 0)
          VWidget(path: r':_(.*)', widget: Container())
      ],
    );
  }
}

```

**Comment by danieldoddjr** [comment]
Ohhh man. How can I buy you a coffee?!

**Comment by danieldoddjr** [comment]
So after building out the dynamic routes I am noticing a harsh flash every time the change notifier updates. I understand this is because I am remaking the key forcing the router to rebuild, updating with the new routes, but also giving me the harsh flash. Is there a softer way to let vrouter know there is updated routes?

**Comment by danieldoddjr** [comment]
So after building out the dynamic routes I am noticing a harsh flash every time the change notifier updates. I understand this is because I am remaking the key forcing the router to rebuild, updating with the new routes, but also giving me the harsh flash. Is there a softer way to let vrouter know there is updated routes?

**Comment by lulupointu** [comment]
You are right, this was ugly. Fixed in `+17`.

Here is an app to reproduce the error for reference:
```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _navigatorKeys = [GlobalKey<NavigatorState>(), GlobalKey<NavigatorState>()];
  var isRed = true;

  GlobalKey<NavigatorState> get navigatorKey => _navigatorKeys[isRed ? 0 : 1];

  @override
  Widget build(BuildContext context) {
    return VRouter(
      navigatorKey: navigatorKey,
      routes: [
        isRed
            ? VWidget(
                path: '/',
                widget: Container(
                  color: Colors.redAccent,
                  child: Center(
                    child: ElevatedButton(
                      onPressed: () => setState(
                        () => isRed = !isRed,
                      ),
                      child: Text('Click me'),
                    ),
                  ),
                ),
              )
            : VWidget(
                path: '/',
                widget: Container(
                  color: Colors.greenAccent,
                  child: Center(
                    child: ElevatedButton(
                      onPressed: () => setState(
                        () => isRed = !isRed,
                      ),
                      child: Text('Click me'),
                    ),
                  ),
                ),
              ),
      ],
    );
  }
}
```

**Comment by danieldoddjr** [comment]
Ohhh man. You just made my week! Perfect!

**Comment by Aerofluxx** [comment]
... and I thought this is by design and do not create a bug report for you @lulupointu ....  

haha ... I can also confirm that the "flashing" is gone now. Looks awesome, thank you!

**Comment by saibotma** [comment]
I tried out the suggested solution, and it works fine. However, obviously (as stated here: https://api.flutter.dev/flutter/material/MaterialApp/navigatorKey.html) all widget state (scroll positions, text field selections, etc.) gets lost when switching the navigator key. Is it possible to somehow keep the state, without putting it into external state management?
